### ISSUE TITLE
Refactor services to use a promise instead of using execute()

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/ng-core-api-client#18]
The way the api client is called without a promise is not very "angular".

https://github.com/Rise-Vision/ng-core-api-client/blob/master/src/js/svc-display.js#L26
vs
https://github.com/Rise-Vision/displays-app/blob/master/js/services/svc-display.js#L32

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc can you clarify what the status of this is? Thanks

**Comment by ezequielc** [comment]
@alex-deaconu Do you think it is worth working on this? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc no. However, we should consider this as a cleanup task together with unifying all our API services under one (this) repo. Right now we have API services in several repos, they are duplicated, etc. I feel the situation is quite bad. Thoughts? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Yes, that is worth refactoring. @ByronDarlison Should we create a card and close this issue? Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;l7sPyxre&#x2F;1106-issues-ng-core-api-client-1-open"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issues: ng-core-api-client {1 open}</a>

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc opened and moved into the backlog of the current epic. Thanks
